{"name": "test_add_member_fail[user3-1111-请填写合法的手机号]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '请填写合法的手机号'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x0000020CA1A6EDD8>\nuser = 'user3', phone = '1111', expect = '请填写合法的手机号'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '请填写合法的手机号'\nE            but: was <None>\n\ntestcases\\test_addMember.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "ce94692f-c2a9-4360-9f6f-e6543f5ae72d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user3'"}, {"name": "phone", "value": "'1111'"}, {"name": "expect", "value": "'请填写合法的手机号'"}], "start": 1626596001490, "stop": 1626596013143, "uuid": "df735c7c-72b6-4992-9034-eb17a6d3322a", "historyId": "234428484d32023bba9f8116ebd2db9d", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "19760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}