{"name": "test_add_member_fail[user3-1111-请填写合法的手机号]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '请填写合法的手机号'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x0000019CF1C4ADA0>\nuser = 'user3', phone = '1111', expect = '请填写合法的手机号'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '请填写合法的手机号'\nE            but: was <None>\n\ntestcases\\test_addMember.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "6c399d48-9768-40b7-b7b9-289eb717d8a9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user3'"}, {"name": "phone", "value": "'1111'"}, {"name": "expect", "value": "'请填写合法的手机号'"}], "start": 1626596801824, "stop": 1626596813289, "uuid": "6d875c9d-d663-47ac-b57d-80ded09ef1c2", "historyId": "234428484d32023bba9f8116ebd2db9d", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "16748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}