{"name": "test_add_member_fail[user3-1111-请填写合法的手机号]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '请填写合法的手机号'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x00000262C8183198>\nuser = 'user3', phone = '1111', expect = '请填写合法的手机号'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '请填写合法的手机号'\nE            but: was <None>\n\ntestcases\\test_addMember.py:29: AssertionError"}, "attachments": [{"name": "log", "source": "53c5f123-7146-478e-8ce4-fb6d315f61ae-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user3'"}, {"name": "phone", "value": "'1111'"}, {"name": "expect", "value": "'请填写合法的手机号'"}], "start": 1626595290777, "stop": 1626595302709, "uuid": "23e2de08-88aa-498f-b84a-c9f23d962ac7", "historyId": "234428484d32023bba9f8116ebd2db9d", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "2536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}